{{- if eq .Values.global.tls.source "letsEncrypt" -}}
apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: "{{ .Values.global.tls.issuerName }}"
spec:
  acme:
    {{- if eq .Values.global.tls.letsEncrypt.environment "production" }}
    server: https://acme-v02.api.letsencrypt.org/directory
    {{- else }}
    server: https://acme-staging-v02.api.letsencrypt.org/directory
    {{- end }}
    email: {{ .Values.global.tls.letsEncrypt.email }}
    privateKeySecretRef:
      name: "{{ .Values.global.tls.issuerName }}-ca-issuer"
    solvers:
    - http01:
        ingress:
          class: {{ .Values.global.tls.letsEncrypt.ingress.class }}
{{- end }}


